#ifndef COLOSSAL_CAVE_ADVENTURE_ACTIONS_H
#define COLOSSAL_CAVE_ADVENTURE_ACTIONS_H

#define ACTION_1_STRING_LENGTH 15
#define ACTION_2_STRING_LENGTH 33
#define ACTION_3_STRING_LENGTH 65
#define ACTION_4_STRING_LENGTH 101
#define ACTION_5_STRING_LENGTH 145
#define ACTION_6_STRING_LENGTH 275
#define ACTION_7_STRING_LENGTH 500
#define AMOUNT_ACTION_1_STRINGS 9
#define AMOUNT_ACTION_2_STRINGS 40
#define AMOUNT_ACTION_3_STRINGS 68
#define AMOUNT_ACTION_4_STRINGS 35
#define AMOUNT_ACTION_5_STRINGS 26
#define AMOUNT_ACTION_6_STRINGS 14
#define AMOUNT_ACTION_7_STRINGS 4
#define ACTION_1_INDEX_ARRAY_SIZE 4
#define ACTION_2_INDEX_ARRAY_SIZE 1
#define ACTION_3_INDEX_ARRAY_SIZE 1
#define ACTION_4_INDEX_ARRAY_SIZE 1
#define ACTION_5_INDEX_ARRAY_SIZE 1
#define ACTION_6_INDEX_ARRAY_SIZE 1
#define ACTION_7_INDEX_ARRAY_SIZE 1

#define LOAD_FROM(NUM) \
	stringToReturn = helper->loadFarStringFromFile(&(FarTextFile) { \
		.farPointer = pgm_get_far_address(actions_##NUM), \
		.maxLengthOfStrings = ACTION_##NUM##_STRING_LENGTH, \
		.sizeOfIndexArray = ACTION_##NUM##_INDEX_ARRAY_SIZE, \
		.amountOfEntries = AMOUNT_ACTION_##NUM##_STRINGS, \
	}, actionNumber); \
	if (stringToReturn != NULL) { return stringToReturn; }

#endif //COLOSSAL_CAVE_ADVENTURE_ACTIONS_H
