#ifndef COLOSSAL_CAVE_ADVENTURE_SHORT_LOCATIONS_H
#define COLOSSAL_CAVE_ADVENTURE_SHORT_LOCATIONS_H

#define SHORT_LOCATION_DESCRIPTION_1_LENGTH 16
#define SHORT_LOCATION_DESCRIPTION_2_LENGTH 31
#define SHORT_LOCATION_DESCRIPTION_3_LENGTH 56
#define SHORT_LOCATION_DESCRIPTION_4_LENGTH 76
#define SHORT_LOCATION_DESCRIPTION_5_LENGTH 187
#define AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_1 2
#define AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_2 51
#define AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_3 29
#define AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_4 11
#define AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_5 8
#define MAX_AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_1_WITH_SAME_LENGTH 13
#define MAX_AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_2_WITH_SAME_LENGTH 2
#define MAX_AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_3_WITH_SAME_LENGTH 1
#define MAX_AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_4_WITH_SAME_LENGTH 14
#define MAX_AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_5_WITH_SAME_LENGTH 1


#define LOAD_FROM(NUM) \
    stringToReturn = stringRepo->loadStringFromFile(&(TextFile) { \
        .farPointer = pgm_get_far_address(shortLocations_##NUM), \
        .maxLengthOfStrings = SHORT_LOCATION_DESCRIPTION_##NUM##_LENGTH, \
        .sizeOfIndexArray = MAX_AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_##NUM##_WITH_SAME_LENGTH, \
        .amountOfEntries = AMOUNT_OF_SHORT_LOCATION_DESCRIPTIONS_##NUM, \
    }, helper, shortLocationNumber); \
    if (stringToReturn != NULL) { return stringToReturn; }
#endif //COLOSSAL_CAVE_ADVENTURE_SHORT_LOCATIONS_H
