#ifndef COLOSSAL_CAVE_ADVENTURE_SHORT_LOCATIONS_H
#define COLOSSAL_CAVE_ADVENTURE_SHORT_LOCATIONS_H

#define SHORT_LOCATION_1_STRING_LENGTH 12
#define SHORT_LOCATION_2_STRING_LENGTH 32
#define SHORT_LOCATION_3_STRING_LENGTH 57
#define SHORT_LOCATION_4_STRING_LENGTH 77
#define SHORT_LOCATION_5_STRING_LENGTH 128
#define AMOUNT_SHORT_LOCATION_1_STRINGS 2
#define AMOUNT_SHORT_LOCATION_2_STRINGS 51
#define AMOUNT_SHORT_LOCATION_3_STRINGS 29
#define AMOUNT_SHORT_LOCATION_4_STRINGS 21
#define AMOUNT_SHORT_LOCATION_5_STRINGS 8
#define SHORT_LOCATION_1_INDEX_ARRAY_SIZE 13
#define SHORT_LOCATION_2_INDEX_ARRAY_SIZE 2
#define SHORT_LOCATION_3_INDEX_ARRAY_SIZE 1
#define SHORT_LOCATION_4_INDEX_ARRAY_SIZE 14
#define SHORT_LOCATION_5_INDEX_ARRAY_SIZE 1

#define LOAD_FROM(NUM) \
	stringToReturn = helper->loadFarStringFromFile(&(FarTextFile) { \
		.farPointer = pgm_get_far_address(shortLocations_##NUM), \
		.maxLengthOfStrings = SHORT_LOCATION_##NUM##_STRING_LENGTH, \
		.sizeOfIndexArray = SHORT_LOCATION_##NUM##_INDEX_ARRAY_SIZE, \
		.amountOfEntries = AMOUNT_SHORT_LOCATION_##NUM##_STRINGS, \
	}, shortLocationNumber); \
	if (stringToReturn != NULL) { return stringToReturn; }

#endif //COLOSSAL_CAVE_ADVENTURE_SHORT_LOCATIONS_H
